version: 0.2

phases:
  install:
    runtime-versions:
        nodejs: 10
  build:
    commands:
      - echo doing the build here!
      - aws cloudformation create-stack --stack-name wow-api-stack --template-body seededjob1.yaml
