version: 0.2

phases:
  install:
    runtime-versions:
        nodejs: 10
  build:
    commands:
      - echo doing the build here!

      - echo "hii"
      - |
        if [ "X$TEMPLATE_PREFIX" = "X" ]; then
          aws s3 cp "$child_template" "s3://$TEMPLATE_BUCKET/$child_template"
        else
          aws s3 cp "$child_template" "s3://$TEMPLATE_BUCKET/$TEMPLATE_PREFIX/$child_template"
        fi
        done
      - aws cloudformation create-stack --stack-name wow-api-stack --template-body file://seededjob1.yaml
