version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - echo doing the build here!
      - stackstate=$(aws cloudformation describe-stacks --stack-name wow-api-stack | jq .Stacks | jq .[0] | jq .StackStatus)
      - echo $stackstate
      - |
          if [ "${stackstate}" = "ROLLBACK_COMPLETE" ]; then
            echo stack is in ROLLBACK_COMPLETE delete it
            aws cloudformation delete-stack --stack-name wow-api-stack
            #aws cloudformation waitstack
          else
            echo do somthing else
          fi
      - echo the end #aws cloudformation create-stack --stack-name wow-api-stack --template-body file://seededjob1.yaml
