version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - | 
          STACK_STATUS=$(aws cloudformation describe-stacks --stack-name wow-api-stack | jq .Stacks | jq .[0] | jq .StackStatus)
          echo $STACK_STATUS
          if [ "$STACK_STATUS" == "ROLLBACK_COMPLETE" ]; then
            echo stack is in ROLLBACK_COMPLETE delete it 1
            aws cloudformation delete-stack --stack-name wow-api-stack
            #aws cloudformation waitstack
          else
            echo do somthing else
          fi
          echo the end #aws cloudformation create-stack --stack-name wow-api-stack --template-body file://seededjob1.yaml
