version: 0.2

phases:
  install:
    runtime-versions:
        nodejs: 10
  build:
    commands:
      - echo doing the build here!

      - echo "hii"
      - |
        if [ "X" = "X" ]; then
          echo was true--
        else
          echo was false--
        fi
        done
      - aws cloudformation create-stack --stack-name wow-api-stack --template-body file://seededjob1.yaml
