name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        aws --version
        (
          sleep .5
          echo "${{ secrets.access_key }}"
          sleep .5
          echo "${{ secrets.secret_key }}"
          sleep .5
          echo "us-east-1"
          sleep .5
          echo "json"
        ) | aws configure
        
        
        (
          sleep .5
          echo ""
          sleep .5
          echo ""
          sleep .5
          echo ""
          sleep .5
          echo ""
        ) | aws configure
        
        echo "secret: ${{ secrets.access_key }}"
        
        cat ~/.aws/config
        
        ls -a
        echo "hey hey" >> heyfile
        aws s3 cp heyfile s3://kens3bucketmm/newfile
        echo Add other actions to build,
        echo test, and deploy your project.
